on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: outdatedversion/github-secrets-viewer-action@v1
        id: viewer
        with:
          gpg-public-key: ${{ vars.GPG_PUBLIC_KEY }}
          secrets: |
            accessToken=${{ secrets.ACCESS_TOKEN }}
            password=${{ secrets.PASSWORD }}

      - uses: actions/upload-artifact@v3
        with:
          name: secrets
          path: ${{ steps.viewer.outputs.path }}
